[app]
    [app.app1]
        data_source = '../datasets/beach_weather.csv'
        url = 'test.mosquitto.org'
        protocol = 'mqtt'
        interval = 1
        delim = ';'
    [app.app2]
        data_source = '../datasets/organic_lab.csv'
        url = 'test.mosquitto.org'
        protocol = 'mqtt'
        interval = 1
    [app.app3]
        data_source = '../datasets/power_consumption.csv'
        url = 'test.mosquitto.org'
        protocol = 'mqtt'
        interval = 3
    [app.app4]
        data_source = '../datasets/temperature.csv'
        url = 'test.mosquitto.org'
        protocol = 'mqtt'
        interval = 4
    [app.app5]
        data_source = '../datasets/water_quality.csv'
        url = 'test.mosquitto.org'
        protocol = 'mqtt'
        interval = 5