[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[metadata]
name = "z0"

[project]
name = "z0"
version = "0.0.1"
description = "z1"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
